dependencies:
- name: nginx-ingress
  version: ">0.0.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kubernetes-dashboard
  version: ">0.0.1"
  repository: https://kubernetes-charts.storage.googleapis.com/  
