#!/bin/bash

# packages all the charts and places them in the dist directory

: ${INPUT_DIR:="../stable"}
: ${OUTPUT_DIR:="../docs"}

for d in $INPUT_DIR/*/ ; do
    echo "$d"
    helm package -d $OUTPUT_DIR $d
done

helm repo index $OUTPUT_DIR
git add ../docs
