#!/bin/bash

# packages all the charts and places them in the dist directory
: ${SCRIPT_DIR:="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"}
: ${INPUT_DIR:="$SCRIPT_DIR/../stable"}
: ${OUTPUT_DIR:="$SCRIPT_DIR/../docs"}

for d in $INPUT_DIR/*/ ; do
    echo "$d"
    (cd $d ; helm dep update)
    helm package -d $OUTPUT_DIR $d
done

helm repo index $OUTPUT_DIR
git add $OUTPUT_DIR
